# Created 2026-04-08 Wed 22:31
#+title: Proposed Thesis Topics
#+author: Daniel McGuiness
#+filetags: :manual:
** Table of Contents                                                  :TOC_5:
- [[#introduction][Introduction]]
  - [[#masters][Masters]]
    - [[#simulation-of-a-synchronous-reluctance-machine][Simulation of a Synchronous Reluctance Machine]]
      - [[#previous-knowledge][Previous Knowledge]]
      - [[#outcome][Outcome]]
  - [[#bachelors][Bachelors]]

* Introduction

Below are the topics currenty proposed.
** Masters

*** Simulation of a Synchronous Reluctance Machine
A synchronous reluctance motor (synRM) is a type of electric motor which operates based on the
principle of magnetic reluctance.

Unlike traditional motors, which rely on electromagnets or permanent magnets, synRMs generate
torque through the rotor's reluctance to the magnetic field generated by the stator. This
results in a highly efficient motor with a simpler construction.
**** Previous Knowledge

The following are required by the students who wishes to partake in the work.

- A good understanding of electric machine design,
- A strong background in C/C++ programming,
- Good knowledge of electrodynamics is preferred.
**** Outcome

A FEM simulation of a synchronous reluctance machine will be conducted. The student is required
to design his/her/their own geometry/mesh using gmsh/CAD and do the necessary simulation
using open-source software such as OpenFOAM, GetDP, or oneLAB to get a performance
analysis. 

After a successful work, the student will gain significant understanding of modelling
electrical machines, understanding meshes for use in simulations and possibly working with
industry standard software (i.e., CERN, Audi, Porsche, ...). 

This work will be used heavily in lectures as showcase for how a machine can be designed and
analysed.
** Bachelors
