# Created 2026-04-10 Fri 07:53
#+title: Proposed Thesis Topics
#+author: Daniel McGuiness
#+filetags: :manual:



** Table of Contents                                                  :TOC_2:
- [[#introduction][Introduction]]
- [[#masters][Masters]]
  - [[#simulation-of-a-synchronous-reluctance-machine][Simulation of a Synchronous Reluctance Machine]]
  - [[#analog-computer-for-solving-odes][Analog Computer for Solving ODEs]]
  - [[#fault-detection-in-electrical-machines][Fault Detection in Electrical Machines]]
- [[#bachelors][Bachelors]]
  - [[#low-resolution-license-plate-recognition][Low Resolution License Plate Recognition]]

* Introduction

Below are the topics currenty proposed. For a quick overview please have a look
at the following table

#+name: TOPIC-NAMES
| Degree | Topic                                                                                              | Availability |
|--------+----------------------------------------------------------------------------------------------------+--------------|
| M.Sc   | [[Simulation of a Synchronous Reluctance Machine][Simulation of a Synchronous Reluctance Machine]] | Yes          |
#+TBLFM: 
* Masters

** Simulation of a Synchronous Reluctance Machine
A synchronous reluctance motor (synRM) is a type of electric motor which
operates based on the principle of magnetic reluctance.

Unlike traditional motors, which rely on electromagnets or permanent magnets,
synRMs generate torque through the rotor's reluctance to the magnetic field
generated by the stator. This results in a highly efficient motor with a simpler
construction. Additional information regarding the motor can be found [[https://easa.com/resources/resource-library/synchronous-reluctance-motor-basics][here]].

The work of the thesis will be the design and simulation of a synRM motor in
a simulation environment. To that end, the student shall work on;

- The calculation of geometrical constraints,
- Generation of proper mesh structure,
- Simulation and optimisation of design.

To achive the aforementioned effectively, the following are required:

- A good understanding of electric machine design,
- A strong background in C/C++ programming,
- Good knowledge of electrodynamics is preferred.

The student is required to use open-source software such as gmsh for mesh
generation and OpenFOAM, GetDP, or oneLAB to get a performance analysis.
** Analog Computer for Solving ODEs

Analog computer are a class of devices in which continuously variable physical
quantities, (i.e., electrical potential) are represented in a way
\textit{analogous} to the corresponding quantities in the problem to be
solved. The analog system is set up according to initial conditions and then
allowed to change freely. Answers to the problem are obtained by measuring the
variables in the analog model and are seeing a resurgence as a good alternative
to digital computers.

There are numerous examples such as the /Phillip's Machine/ which was used to
determine the economic process at a national level using fluidic logic, or the
/Robert's Machine/ which was used to determine the tides.

Project -- Design, test, and construct an electrical circuit which is capable of
solving 1st- and 2nd-order ODEs given to the circuit as input.

As an example, using the circuit, the behaviour of a mass-damper-spring system
will be simulated:

$m \frac{d^2x}{dt^2} + c\frac{dx}{dt} + kx = f(x),$

where the values of the mass ($m$), damper ($c$) and spring ($k$) will be set
using a signal generator.
*** Previous Knowledge

The student is required to have a working knowledge of:

- Working understanding with PCBs,
- Circuit design and soldering.
- Understanding ODEs are a plus.
*** Outcome

The outcome a working example of an analog computer constructed from electrical
circuit components. The student will also gain a strong understanding with
circuit design.

The outcome of this work will be used extensively in *M.Sc Higher Mathematics I*
to showcase ODE solving and will be used in demonstrations for outreach and
pedagogic activities.
** Fault Detection in Electrical Machines

Electrical machines, while the backbone of industry, are prone to various faults and require
constant monitoring to ensure safe and dependable functioning. 

A potential fault in electrical machinery results in unscheduled downtime, necessitating the
prompt assessment of any abnormal circumstances in rotating electrical machines. 

The work will require to implement machine learning algorithms for the service of fault
detection.
*** Previous Knowledge

The student is required to have a working knowledge of:

- A good understanding of machine learning/signal processing is preferred,
- A strong background in programming,
- Working knowledge of electrodynamics is beneficial.
*** Outcome

The outcome will be a work producing a possible novel approach to detecting electrical faults
in an electrical motor.

The student will gain significant experience working with signal processing and programming
and developing large machine learning algorithms.
* Bachelors

** Low Resolution License Plate Recognition
