
# Masters Topics



## Simulation of a Synchronous Reluctance Machine

A synchronous reluctance motor is a type of electric motor which operates on the
principles of *magnetic reluctance*.

Unlike traditional motors, which rely on electromagnets or permanent magnets,
synchronous reluctance motors generate torque through the rotor's reluctance to
the magnetic field which is generated by the stator.

This results in a highly efficient motor with a simpler construction.

Additional information on these kinds of motor can be found [here](https://easa.com/resources/resource-library/synchronous-reluctance-motor-basics).

The work of the thesis will be the design and simulation of a synchronous
reluctance motor within a simulation environment. To that end, the student will
have to work on;

-   The calculation of geometrical constraints,
-   Generation of proper mesh structure,
-   Simulation and optimization of design.

To achieve the aforementioned requirements effectively, the following
experiences are required:

-   A good understanding of electric machine design,
-   A strong background in C/C++ programming,
-   Good knowledge of electrodynamics is preferred.

The student is required to use open-source software such as `gmsh` for mesh
generation and `OpenFOAM`, `GetDP` to get a performance analysis.


## Analog Computer for Solving ODEs

Analog computer are a class of devices whereby continuously variable physical
quantities, (i.e., electrical potential) are represented in a way that is
analogous to the corresponding quantities in the problem to be solved. The
analog system is set up according to initial conditions and then allowed to
change freely.

Answers to the problem are obtained by measuring the variables in the analog
model and are seeing a resurgence as a good alternative to digital computers.

There are numerous examples such as the [Phillip's Machine](https://www.sciencemuseum.org.uk/objects-and-stories/how-does-economy-work) which was used to
determine the economic process at a national level using fluidic logic, or the
[Robert's Machine](https://en.wikipedia.org/wiki/Tide-predicting_machine) which was used to determine the tides. An interesting article
by [Quanta magazine](https://www.quantamagazine.org/what-is-analog-computing-20240802/) on Analog computers is also worth a quick read.

The work of this thesis is to design, test, and construct an electrical circuit
which is capable of solving 1st- and 2nd-order Ordinary Differential Equations
given to the circuit as input.

As an example, using the circuit, the behavior of a mass-damper-spring system
will be simulated:

$$m \frac{d^2x}{dt^2} + c\frac{dx}{dt} + kx = f(x),$$

where the values of the mass ($m$), damper ($c$) and spring ($k$) will be set
using a signal generator. To design this computer, the student will have to work
on;

-   The Design of the circuit logic which allows configurable options to solve a
    wide variety of equations,
-   Implementation of analog circuits and designing appropriate filters to
    minimize circuit noise.


### Test

To achieve the aforementioned effectively, the following are required:

-   Working understanding with Printed Circuit Boards,
-   Circuit design and soldering.
-   Understanding Ordinary Differential Equations are a plus.


## Fault Detection in Electrical Machines

Electrical machines, while the backbone of residential, commercial and
industrial settings, are nevertheless, prone to numerous faults and require
constant monitoring to ensure safe and dependable functioning.

A potential fault in electrical machinery results in unscheduled downtime,
necessitating the prompt assessment of any abnormal circumstances in rotating
electrical machines.

The work will require to implement machine learning algorithms for the service
of fault detection. To achieve the required application, the student is required
to have a working knowledge of:

-   A good understanding of machine learning/signal processing is preferred,
-   A strong background in programming,
-   Working knowledge of electrodynamics is beneficial.

The outcome will be a work producing a possible novel approach to detecting
electrical faults in an electrical motor.

The student will gain significant experience working with signal processing and
programming and developing large machine learning algorithms.


## Vector Control of Induction Motors using Embedded Computing

While AC motors have shown to be reliable and performing well, it was not the
case 30+ years ago. Then, majority of machines used in industry would have been
based on DC machines. The primary reason for their abundance was due to their
simplicity in control. Then, with the advent of vector control AC machines were
able to catch up in terms of efficiency and control.

This thesis will focus on designing the vector control for the use of primarily
induction machines which the student will have access to. The coding and the
logic of the vector control will be implemented on an embedded computing, which
will the ESP32.

To achieve this construction the student should have a working knowledge of:

-   A solid understanding of the principles of vector control and induction
    machine modeling.
-   Knowledge of designing an inverter,
-   Previous experience on working with Embedded Systems or good knowledge in C.

The outcome will be a fully functional test-bed with an induction motor
controlled using vector control method.
